### ISSUE TITLE
Weird border change after update

### ISSUE THREAD

**Issue by daxisunder** [ErikReider/SwayNotificationCenter#596]
After the last update, the notification border changed color and doubled in thickness. It was the same as notification center border. Nothing changed in the config. 

https://github.com/user-attachments/assets/c6198790-114a-4b48-b0c1-595e1b3b04df

**Comment by ErikReider** [comment]
Which version are you using? The latest stable or master?

**Comment by daxisunder** [comment]
> Which version are you using? The latest stable or master?

Latest stable. If I downgrade swaync to 0.11.0 the issue disappears.

**Comment by ErikReider** [comment]
Have you tried 0.12.1?

**Comment by daxisunder** [comment]
> Have you tried 0.12.1?

Yes, the issue persists.

**Comment by ErikReider** [comment]
Could you provide logs? (follow the instructions of the issue report)

**Comment by ErikReider** [comment]
Removing everything in your .config/gtk-4.0/gtk.css and unset the GTK_THEME variable should fix this

**Comment by JaKooLit** [comment]
> Removing everything in your .config/gtk-4.0/gtk.css and unset the GTK_THEME variable should fix this

Unfortunately didnt work.

I have same issue as op

here is the output of G_MESSAGES_DEBUG=all swaync 

> G_MESSAGES_DEBUG=all swaync  
** INFO: 19:32:16.837: functions.vala:172: Looking for config file in these directories:
	- /home/ja/.config/swaync/config.json
	- /etc/xdg/swaync/config.json
	- /usr/local/etc/xdg/swaync/config.json
(process:4659): GLib-GIO-DEBUG: 19:32:16.839: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
** Message: 19:32:16.839: configModel.vala:331: Loading Config: "/home/ja/.config/swaync/config.json"

(process:4659): Json-WARNING **: 19:32:16.840: Failed to deserialize "image-visibility" property of type "SwayNotificationCenterImageVisibility" for an object of type "SwayNotificationCenterConfigModel"
** (process:4659): DEBUG: 19:32:16.840: configModel.vala:359: {
  "ignore-gtk-theme" : true,
  "positionX" : "center",
  "positionY" : "top",
  "layer" : "overlay",
  "layer-shell" : true,
  "layer-shell-cover-screen" : true,
  "cssPriority" : "user",
  "timeout" : 6,
  "timeout-low" : 3,
  "timeout-critical" : 0,
  "transition-time" : 200,
  "keyboard-shortcuts" : true,
  "notification-grouping" : true,
  "image-visibility" : "when-available",
  "notification-window-width" : 300,
  "notification-window-height" : -1,
  "notification-window-preferred-output" : "",
  "hide-on-clear" : false,
  "hide-on-action" : true,
  "text-empty" : "No Notifications",
  "control-center-positionX" : "none",
  "control-center-positionY" : "none",
  "control-center-margin-top" : 5,
  "control-center-margin-bottom" : 0,
  "control-center-margin-left" : 0,
  "control-center-margin-right" : 0,
  "control-center-layer" : "top",
  "control-center-exclusive-zone" : true,
  "categories-settings" : {  },
  "notification-visibility" : {  },
  "scripts" : {  },
  "script-fail-notify" : true,
  "fit-to-screen" : false,
  "relative-timestamps" : true,
  "control-center-height" : 720,
  "control-center-width" : 450,
  "control-center-preferred-output" : "",
  "notification-2fa-action" : true,
  "notification-inline-replies" : false,
  "notification-icon-size" : 24,
  "notification-body-image-height" : 100,
  "notification-body-image-width" : 200,
  "widgets" : [
    "dnd",
    "buttons-grid",
    "title",
    "notifications"
  ],
  "widget-config" : {
    "title" : {
      "text" : "Notifications",
      "clear-all-button" : true,
      "button-text" : "Clear"
    },
    "dnd" : {
      "text" : "Do Not Disturb"
    },
    "label" : {
      "max-lines" : 1,
      "text" : "Notification"
    },
    "mpris" : {
      "image-size" : 10,
      "image-radius" : 0
    },
    "volume" : {
      "label" : "?"
    },
    "backlight" : {
      "label" : "?"
    },
    "buttons-grid" : {
      "actions" : [
        {
          "label" : "?",
          "command" : "bash -c $HOME/.config/hypr/scripts/Wlogout.sh"
        },
        {
          "label" : "?",
          "command" : "bash -c $HOME/.config/hypr/scripts/LockScreen.sh"
        },
        {
          "label" : "?",
          "command" : "hyprctl dispatch exit"
        },
        {
          "label" : "?",
          "command" : "bash -c $HOME/.config/hypr/scripts/AirplaneMode.sh"
        },
        {
          "label" : "?",
          "command" : "pactl set-sink-mute @DEFAULT_SINK@ toggle"
        },
        {
          "label" : "?",
          "command" : "blueman-manager"
        }
      ]
    }
  }
}
(process:4659): GLib-DEBUG: 19:32:16.840: unsetenv() is not thread-safe and should not be used after threads are created
(process:4659): Gdk-DEBUG: 19:32:16.844: Using portal setting for org.gnome.fontconfig serial: 0
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy disable-microphone
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy disable-camera
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy old-files-age
(process:4659): Gdk-DEBUG: 19:32:16.844: Using portal setting for org.gnome.desktop.privacy remember-recent-files: true
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy disable-sound-output
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy send-software-usage-stats
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy report-technical-problems
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy remove-old-trash-files
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy remove-old-temp-files
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy privacy-screen
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy usb-protection
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy usb-protection-level
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy remember-app-usage
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy show-full-name-in-top-bar
(process:4659): Gdk-DEBUG: 19:32:16.844: Ignoring portal setting for org.gnome.desktop.privacy hide-identity
(process:4659): Gdk-DEBUG: 19:32:16.844: Using portal setting for org.gnome.desktop.privacy recent-files-max-age: -1
(process:4659): Gdk-DEBUG: 19:32:16.844: Using portal setting for org.gnome.desktop.a11y.interface show-status-shapes: false
(process:4659): Gdk-DEBUG: 19:32:16.844: Using portal setting for org.gnome.desktop.a11y.interface high-contrast: false
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.a11y always-show-universal-access-status
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.a11y always-show-text-caret: false
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface toolkit-accessibility
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface gtk-color-palette
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface can-change-accels
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface document-font-name
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface enable-animations: true
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface cursor-blink: true
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface clock-show-weekday
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface icon-theme: 'Flat-Remix-Blue-Dark'
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface gtk-im-preedit-style
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface scaling-factor
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface menus-have-tearoff
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface cursor-size: 24
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface clock-show-seconds
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface gtk-im-module: ''
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface gtk-timeout-initial
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface accent-color
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface gtk-theme: 'Flat-Remix-GTK-Blue-Dark'
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface gtk-color-scheme
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface clock-show-date
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface cursor-blink-time: 1200
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface toolbar-icons-size
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface font-antialiasing: 'grayscale'
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface toolbar-style
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface enable-hot-corners
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface monospace-font-name
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface gtk-timeout-repeat
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface overlay-scrolling: true
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface cursor-blink-timeout: 10
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface gtk-key-theme
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface toolbar-detachable
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface font-rendering: 'automatic'
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface cursor-theme: 'Bibata-Modern-Amber'
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface avatar-directories
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface gtk-im-status-style
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface menubar-detachable
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface text-scaling-factor: 1.25
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface show-battery-percentage
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface clock-format
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface menubar-accel
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface gtk-enable-primary-paste: true
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface color-scheme
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.interface locate-pointer
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface font-rgba-order: 'rgb'
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface font-hinting: 'slight'
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.interface font-name: 'FantasqueSansM Nerd Font Propo Bold 14'
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.sound theme-name: 'freedesktop'
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.sound event-sounds: true
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.sound input-feedback-sounds: false
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.sound allow-volume-above-100-percent
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.peripherals.mouse left-handed
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.peripherals.mouse double-click: 400
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.peripherals.mouse natural-scroll
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.peripherals.mouse middle-click-emulation
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.peripherals.mouse speed
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.peripherals.mouse accel-profile
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.peripherals.mouse drag-threshold: 8
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.input-sources sources
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.input-sources mru-sources
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.input-sources show-all-sources
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.input-sources current
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.input-sources xkb-options
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.input-sources xkb-model
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.input-sources per-window
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.calendar show-weekdate
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences theme
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences focus-new-windows
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences disable-workarounds
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences num-workspaces
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences titlebar-uses-system-font
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences raise-on-click
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences titlebar-font
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences resize-with-right-button
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences auto-raise
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.wm.preferences action-right-click-titlebar: 'menu'
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences mouse-button-modifier
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.wm.preferences action-double-click-titlebar: 'toggle-maximize'
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences workspace-names
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences visual-bell-type
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.wm.preferences action-middle-click-titlebar: 'none'
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences focus-mode
(process:4659): Gdk-DEBUG: 19:32:16.845: Using portal setting for org.gnome.desktop.wm.preferences button-layout: 'appmenu:close'
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences auto-raise-delay
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences audible-bell
(process:4659): Gdk-DEBUG: 19:32:16.845: Ignoring portal setting for org.gnome.desktop.wm.preferences visual-bell
(process:4659): Adwaita-DEBUG: 19:32:16.871: Setting org.freedesktop.appearance.accent-color of type (ddd) not found
(process:4659): GLib-GIO-DEBUG: 19:32:16.872: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(process:4659): dconf-DEBUG: 19:32:16.872: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
(process:4659): dconf-DEBUG: 19:32:16.872: watch_established: "/org/gnome/desktop/interface/" (establishing: 1)
(process:4659): dconf-DEBUG: 19:32:16.894: watch_fast: "/org/erikreider/swaync/" (establishing: 0, active: 0)
(process:4659): dconf-DEBUG: 19:32:16.894: watch_established: "/org/erikreider/swaync/" (establishing: 1)
An instance of SwayNotificationCenter is already 

> running!

**Comment by daxisunder** [comment]
I just noticed, the problem persists on 0.11.0 too, it wasn't visible because of dark background. But this looks different, first one is like a fat border, rounded corners, same thickness on all sides, his one is like a small window behind the notification popup, and it stays a moment behind after the popup closes. It's better visible IRL, it stays for like half a second.

https://github.com/user-attachments/assets/02674017-8b12-49ff-8ee5-db661c21c056

And now I'm getting this on latest stable:

https://github.com/user-attachments/assets/a1b6187f-957f-49b9-859c-e6f5e3582284

**Comment by daxisunder** [comment]
```
** INFO: 01:06:42.415: functions.vala:150: Looking for CSS file in these directories:
        - /etc/xdg/swaync/style.css
        - /usr/local/etc/xdg/swaync/style.css
** Message: 01:06:42.415: functions.vala:98: Loading CSS: "/etc/xdg/swaync/style.css"
** INFO: 01:06:42.416: functions.vala:150: Looking for CSS file in these directories:
        - /home/daxis/.config/swaync/style.css
        - /etc/xdg/swaync/style.css
        - /usr/local/etc/xdg/swaync/style.css
** Message: 01:06:42.416: functions.vala:112: Loading CSS: "/home/daxis/.config/swaync/style.css"
```

**Comment by ErikReider** [comment]
Oh getting the same thing, it's your CSS that's borked

**Comment by ErikReider** [comment]
Dude, the black background is caused by this in your CSS…

<img width="464" height="89" alt="Image" src="https://github.com/user-attachments/assets/b630b15f-dae0-4220-9b94-36823b027934" />

Still looking for the border cause though

**Comment by ErikReider** [comment]
Ok I think I know what's going on, I forgot that I removed all the `@define-color` variables, which defaults to white when not defined. Working on a fix :D

**Comment by ErikReider** [comment]
<img width="667" height="557" alt="Image" src="https://github.com/user-attachments/assets/5103499b-df44-4477-84e1-0cb9a840e89a" />

This looks a little bit better

**Comment by daxisunder** [comment]
I'm still seeing the white border, but I might be doing something wrong, this is a bit above my pay grade, as they say. I tried to follow the directions, though, and it built without errors.

**Comment by JaKooLit** [comment]
> [@daxisunder](https://github.com/daxisunder) Are you able to test the PR linked above?
> 
> You can use the new "system CSS" by compiling and running swaync like this: `meson setup build --wipe && meson compile -C build && ./build/src/swaync --custom-system-css ./build/data/style.css`

tested your new PR

still same

here is what I have done. Dont know if is correct step though but let me know if I have done wrong

install swaync-git from aur

clone the repo
and ran this after cd into repo
`meson setup build --wipe && meson compile -C build && ./build/src/swaync --custom-system-css ./build/data/style.css`

**Comment by JaKooLit** [comment]
> What was the output of running that command?
> 
> I'm not really sure what this could be as none of you are using a custom GTK theme, nothing in the ~/.config/gtk-4.0/gtk.css file, and no weird theme issues. Right?

not sure if you want me to put the whole output of building

it is kinda long so I just post here the last part including when it started

NOTE: I execute "pkill swaync" first before running above

`configModel.c:5770:1: note: ‘sway_notification_center_config_model_real_serialize_property’ declared here
configModel.c:9975:82: warning: unused parameter ‘iface_data’ [-Wunused-parameter]
configModel.c: In function ‘sway_notification_center_config_model_instance_init’:
configModel.c:9988:63: warning: unused parameter ‘klass’ [-Wunused-parameter]
configModel.c: At top level:
configModel.c:7652:1: warning: ‘block4_data_ref’ defined but not used [-Wunused-function]
[62/62] Linking target src/swaync


** Message: 18:10:10.991: configModel.vala:329: Loading Config: "/home/ja/.config/swaync/config.json"

(process:19276): Json-WARNING **: 18:10:10.991: Failed to deserialize "image-visibility" property of type "SwayNotificationCenterImageVisibility" for an object of type "SwayNotificationCenterConfigModel"

(process:19276): Gtk-WARNING **: 18:10:11.004: Theme parser error: gtk.css:4970:12-17: "shade" is not a valid color name.

(process:19276): Gtk-WARNING **: 18:10:11.004: Theme parser error: gtk.css:5030:12-17: "shade" is not a valid color name.

(process:19276): Gtk-WARNING **: 18:10:11.004: Theme parser error: gtk.css:5057:12-15: "mix" is not a valid color name.

(process:19276): Gtk-WARNING **: 18:10:11.004: Theme parser error: gtk.css:5061:12-15: "mix" is not a valid color name.

(process:19276): Gtk-WARNING **: 18:10:11.004: Theme parser warning: gtk.css:5262:3-5263:1: Expected ';' at end of block

(process:19276): Gtk-WARNING **: 18:10:11.005: Theme parser error: gtk.css:5293:3-19: No property named "-gtk-icon-effect"
** Message: 18:10:11.053: functions.vala:87: Loading CSS: "./build/data/style.css"
** Message: 18:10:11.054: functions.vala:100: Loading CSS: "/home/ja/.config/swaync/style.css"

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:21:5-22:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:62:5-63:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:76:5-77:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:87:5-88:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:92:5-93:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:97:5-98:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:101:5-102:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:109:5-110:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:118:5-119:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:124:5-125:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:128:5-129:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:134:5-135:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:142:5-143:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:151:5-152:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:159:5-160:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:170:5-171:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:174:5-175:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:182:5-183:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:230:5-231:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:235:5-236:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:266:5-267:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:270:5-271:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:286:5-287:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:292:5-293:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:297:5-298:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:302:5-303:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:311:5-312:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:316:5-317:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:324:2-325:1: Expected ';' at end of block

(swaync:19276): Gtk-WARNING **: 18:10:11.054: Theme parser warning: style.css:333:5-334:1: Expected ';' at end of block

** (swaync:19276): CRITICAL **: 18:10:11.060: baseWidget.vala:50: notifications: Config not found! Using default config...

** Message: 18:10:11.061: factory.vala:54: Loading widget: dnd
** Message: 18:10:11.061: factory.vala:54: Loading widget: buttons-grid

** (swaync:19276): CRITICAL **: 18:10:11.063: sway_notification_center_widgets_mpris_mpris_player_update_album_art: assertion 'metadata != NULL' failed

** (swaync:19276): CRITICAL **: 18:10:11.063: sway_notification_center_widgets_mpris_mpris_player_update_title: assertion 'metadata != NULL' failed

** (swaync:19276): CRITICAL **: 18:10:11.063: sway_notification_center_widgets_mpris_mpris_player_update_sub_title: assertion 'metadata != NULL' failed

** (swaync:19276): CRITICAL **: 18:10:11.063: sway_notification_center_widgets_mpris_mpris_player_update_buttons: assertion 'metadata != NULL' failed
** Message: 18:10:11.063: factory.vala:54: Loading widget: mpris
** Message: 18:10:11.063: factory.vala:54: Loading widget: volume

** (swaync:19276): WARNING **: 18:10:11.063: backlightUtil.vala:41: Could not find device /sys/class/backlight/intel_backlight/brightness

** Message: 18:10:11.064: factory.vala:54: Loading widget: backlight
** Message: 18:10:11.064: factory.vala:54: Loading widget: title
** Message: 18:10:11.064: factory.vala:16: Loading widget: widget-notifications

** (swaync:19276): CRITICAL **: 18:10:11.064: baseWidget.vala:50: notifications: Config not found! Using default config...` 

>

**Comment by JaKooLit** [comment]
something is from the old config which causing it it seems

I renamed style.css on ~/.config/swaync/  to style.css.bak

and it works no issue but of course no colors wanted

contents of my style.css
[https://raw.githubusercontent.com/JaKooLit/Hyprland-Dots/refs/heads/main/config/swaync/style.css](url)

**Comment by daxisunder** [comment]
> What was the output of running that command?

It's the huge meson output, I'll post it if you want me to. This is the only part that caught my eye, if it means anything important: ```** (swaync:1218221): CRITICAL **: 09:20:45.048: base Widget.vala:50: notifications: Config not found! Using default config... ```

> I'm not really sure what this could be as none of you are using a custom GTK theme, nothing in the ~/.config/gtk-4.0/gtk.css file, and no weird theme issues. Right?

I'm using a custom theme, but the issue persist even on default Adwaita theme and I don't have ~/.config/gtk-4.0 folder at all. What's interesting to me is that everything was working perfectly fine on 0.12.0, the issue started on 0.12.1, but now it persists even if downgraded to 0.12.0, it disappears only on 0.11.0

**Comment by ErikReider** [comment]
> m using a custom theme, but the issue persists even on default Adwaita theme and I don't have ~/.config/gtk-4.0 folder at all. What's interesting to me is that everything was working perfectly fine on 0.12.0, the issue started on 0.12.1, but now it persists even if downgraded to 0.12.0, it disappears only on 0.11.0.

Then it sounds like your CSS (`.config/swaync/style.css`) is borked. What happens if you delete everything in that file and restart swaync?

**Comment by daxisunder** [comment]
> Then it sounds like your CSS (`.config/swaync/style.css`) is borked. What happens if you delete everything in that file and restart swaync?

If I remove style.css everything's fine, with no customizations. What's bugging me is what's changed in 0.12.1 so this happens? My style.css is the same since forever. And why was it working on 0.12.0 before, but now it doesn't?
